version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_USER=sa
      - DB_PASSWORD=123@123qw
      - DB_HOST=db
      - DB_PORT=1433
      - MASTER_DB_NAME=master
      - ITISAL_DB_NAME=ITISAL
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123@123qw
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=1536
      - MSSQL_AGENT_ENABLED=false
    volumes:
      - mssql_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 1.8GB
        reservations:
          memory: 1.5GB
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "123@123qw" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

volumes:
  mssql_data: 